/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pa03_constsoft;

/**
 *
 * @author juan.ortiz.l_kavak
 */
public class GUIGestiónMeseros extends javax.swing.JFrame {

    /**
     * Creates new form GUIGestiónMeseros
     */
    public GUIGestiónMeseros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkMesa3 = new javax.swing.JCheckBox();
        chkMesa2 = new javax.swing.JCheckBox();
        chkMesa1 = new javax.swing.JCheckBox();
        chkMesa4 = new javax.swing.JCheckBox();
        chkMesa5 = new javax.swing.JCheckBox();
        chkMesa6 = new javax.swing.JCheckBox();
        chkMesa7 = new javax.swing.JCheckBox();
        chkMesa13 = new javax.swing.JCheckBox();
        chkMesa8 = new javax.swing.JCheckBox();
        chkMesa14 = new javax.swing.JCheckBox();
        chkMesa9 = new javax.swing.JCheckBox();
        chkMesa15 = new javax.swing.JCheckBox();
        chkMesa10 = new javax.swing.JCheckBox();
        chkMesa16 = new javax.swing.JCheckBox();
        chkMesa11 = new javax.swing.JCheckBox();
        chkMesa17 = new javax.swing.JCheckBox();
        chkMesa12 = new javax.swing.JCheckBox();
        chkMesa18 = new javax.swing.JCheckBox();
        cmbNombreMesero = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkMesa3.setText("Mesa 3");

        chkMesa2.setText("Mesa 2");

        chkMesa1.setText("Mesa 1");

        chkMesa4.setText("Mesa 4");

        chkMesa5.setText("Mesa 5");

        chkMesa6.setText("Mesa 6");

        chkMesa7.setText("Mesa 7");

        chkMesa13.setText("Mesa 13");

        chkMesa8.setText("Mesa 8");

        chkMesa14.setText("Mesa 14");

        chkMesa9.setText("Mesa 9");

        chkMesa15.setText("Mesa 15");

        chkMesa10.setText("Mesa 10");

        chkMesa16.setText("Mesa 16");

        chkMesa11.setText("Mesa 11");

        chkMesa17.setText("Mesa 17");

        chkMesa12.setText("Mesa 12");

        chkMesa18.setText("Mesa 18");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkMesa6)
                    .addComponent(chkMesa5)
                    .addComponent(chkMesa4)
                    .addComponent(chkMesa1)
                    .addComponent(chkMesa2)
                    .addComponent(chkMesa3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkMesa13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkMesa14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkMesa15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(chkMesa16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkMesa17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkMesa12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkMesa18)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa1)
                    .addComponent(chkMesa7)
                    .addComponent(chkMesa13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa2)
                    .addComponent(chkMesa8)
                    .addComponent(chkMesa14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa3)
                    .addComponent(chkMesa9)
                    .addComponent(chkMesa15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa4)
                    .addComponent(chkMesa10)
                    .addComponent(chkMesa16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa5)
                    .addComponent(chkMesa11)
                    .addComponent(chkMesa17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMesa6)
                    .addComponent(chkMesa12)
                    .addComponent(chkMesa18))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        cmbNombreMesero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsignar.setText("Asignar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ASIGNACIÓN DE MESAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNombreMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(cmbNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAsignar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGestiónMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGestiónMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGestiónMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGestiónMeseros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGestiónMeseros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JCheckBox chkMesa1;
    private javax.swing.JCheckBox chkMesa10;
    private javax.swing.JCheckBox chkMesa11;
    private javax.swing.JCheckBox chkMesa12;
    private javax.swing.JCheckBox chkMesa13;
    private javax.swing.JCheckBox chkMesa14;
    private javax.swing.JCheckBox chkMesa15;
    private javax.swing.JCheckBox chkMesa16;
    private javax.swing.JCheckBox chkMesa17;
    private javax.swing.JCheckBox chkMesa18;
    private javax.swing.JCheckBox chkMesa2;
    private javax.swing.JCheckBox chkMesa3;
    private javax.swing.JCheckBox chkMesa4;
    private javax.swing.JCheckBox chkMesa5;
    private javax.swing.JCheckBox chkMesa6;
    private javax.swing.JCheckBox chkMesa7;
    private javax.swing.JCheckBox chkMesa8;
    private javax.swing.JCheckBox chkMesa9;
    private javax.swing.JComboBox<String> cmbNombreMesero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
